name: WoolDyer
main: haveric.woolDyer.WoolDyer
version: 1.0.5
author: haveric
dev-url: http://dev.bukkit.org/server-mods/wooldyer/
description: >
             Dye wool that is already placed
commands:
    wooldyer:
        aliases: [wd]
        description: Dye wool that is already placed
        usage:
permissions:
    wooldyer.*:
        description: Gives access to all WoolDyer commands
        children:
            wooldyer.dye: true
    wooldyer.dye:
        description: Allows user to dye wool
        default: false
        
    