name: WoolDyer
main: haveric.woolDyer.WoolDyer
version: 1.0.1
author: haveric
dev-url: http://dev.bukkit.org/server-mods/wooldyer/
description: >
             Dye wool that is already placed
commands:
  wooldyer:
    description: Dye wool that is already placed
    usage: