name: WoolDyer
main: haveric.woolDyer.WoolDyer
version: 1.1.0
author: haveric
website: https://dev.bukkit.org/projects/wooldyer/
dev-url: https://dev.bukkit.org/projects/wooldyer/
api-version: 1.14
description: >
             Dye wool that is already placed
commands:
    wooldyer:
        aliases: [wd]
        description: Dye wool that is already placed
        usage:
permissions:
    wooldyer.*:
        description: Gives access to all WoolDyer commands
        children:
            wooldyer.dye: true
    wooldyer.dye:
        description: Allows user to dye wool
        default: false
        
    